CS1-44: Fee Reversals
canopy1/api-docs pull request #181
Opened 2021-05-25 00:55 UTC by vikram-canopy

## Description of the change

> Description here

- added fee reversal endpoint modeled off of payment reversal endpoint
- removed unused paymentReversalInput & request (fields not utilized by mw)

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]()

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-05-25 01:01 UTC, goodgoodwish approved these changes
Looks good.

2021-05-25 01:03 UTC, ps2-controller requested changes

2021-05-25 01:03 UTC, ps2-controller commented on openapi.json
> -        "requestBody": {
Why deleting this? The parameters of the request body are optional, but should be honored by the API, consistent with our general line item schema

2021-05-25 01:03 UTC, ps2-controller commented on openapi.json
> +          },
Similarly, don't think the request body here should be left out, at least external fields as a pattern should remain consistent.

2021-05-25 01:17 UTC, vikram-canopy commented on openapi.json
> -        "requestBody": {
I see. @ps2-controller the mw doesn't currently parse it and pass it to the data API so it seemed vestigial. Should we instead make mw changes to ensure its parsed and passed appropriately?

2021-05-25 01:18 UTC, ps2-controller commented on openapi.json
> -        "requestBody": {
Yeah -- you can make the case to descope it if it adds a lot of complexity, but I don't think it should since we're already writing to line items table for this

2021-05-27 22:29 UTC, ps2-controller commented on schemas/CreateFeeWaiverInput.json
> +    "effective_at": {
hmm per SOR discussion, we're not actually able to support this in initial version like I'd previously thought, right? backdated reversals should later have a validation that allows them to only be run in migration mode?

2021-05-27 22:31 UTC, ps2-controller approved these changes

2021-05-27 22:47 UTC, merged