Add spend_limit parameter for cards
canopy1/api-docs pull request #194
Opened 2021-06-01 21:10 UTC by kpamaran

## Description of the change

Add spend_limit parameter for card creation/update.

Of interest is that we're enforcing spend_limit in our system and not relying on setting an external one like in Lithic. Hence why spend_limit is located a level above the lithic-parameter.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

[PCV1-40](https://canopyservicing.atlassian.net/browse/PCV1-40)

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review

- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2021-06-02 14:59 UTC, ps2-controller requested changes

2021-06-02 17:45 UTC, kpamaran commented on schemas/CreateCustomerAccountCardInput.json
>      "lithic": {
That deserves a separate PR

2021-06-03 15:49 UTC, kpamaran commented
@ps2-controller other than the BIN-token card parameter is this good to go?

2021-06-03 16:06 UTC, ps2-controller approved these changes

2021-06-03 20:08 UTC, merged