Adding tags to interest rate schema
canopy1/api-docs pull request #345
Opened 2022-01-06 20:17 UTC by phorical

## Description

> Give your teammates a high level overview of what's happening. What changes are being made? What is in scope or out of scope?

## Testing

> Teach your teammates how to run and check that your work does what you say it does.

- [ ] Is QA required?

## Related issues

> Help your teammates keep track of work. Link relevant PRs and tickets.
>
> You can link Linear tickets by ID within the title or add the entire Linear ticket URL inside the description. GH integrations will link tickets and PRs.

2022-01-06 22:36 UTC, michael-canopy approved these changes

2022-01-06 23:40 UTC, ps2-controller requested changes

2022-01-06 23:40 UTC, ps2-controller commented on schemas/InterestRate.json
> +      "tags": {
Object needs `properties` attribute. 
I need a bit of a refresher for what we want to accomplish with `tags` --- If we're using this to allow arbitrary additional properties, we should follow the `external_fields` pattern used elsewhere in the API

2022-01-06 23:43 UTC, michael-canopy commented on schemas/InterestRate.json
> +      "tags": {
Ooh that's right. I'm a little rusty on OpenAPI specs nowadays...

2022-01-06 23:44 UTC, ps2-controller commented on schemas/InterestRate.json
> +      "tags": {
All good! I'm surprised it built actually, maybe it's not _technically_ required, but practically speaking it is

2022-01-07 15:18 UTC, phorical commented on schemas/InterestRate.json
> +      "tags": {
We had talked about this a bit @ps2-controller as a way to generalize the need to have an account/interest rate somehow marked as coming from SCRA. This allows further expansion into use cases like notes on the interest rate or denoting specific promos that apply. I can add the `scra` properties here or we could talk about refactoring this to something else

2022-01-10 15:29 UTC, ps2-controller approved these changes

2022-01-10 15:31 UTC, ps2-controller commented
Approved, but qq -- does inclusion of this tag affect system behavior in any way? If so, that'd be good to document in its description.

2022-01-10 15:35 UTC, phorical commented
@ps2-controller The scra_start and scra_end functionality uses this tag under the hood. That being said, it can be expanded beyond just SCRA for future use cases. I am not expecting our customers to include any tags for now; I expect them to use the scra_start and _end functions which will create the `{"scra": true}` tag for them on the interest rate.

2022-01-10 15:39 UTC, ps2-controller commented
Gotcha, makes sense!
One last note --- should these tags print booleans, or nested information? I think with SCRA, there's an "expected" end date that doesn't actually map to the intentional system end date, which is infinity, right? Would this be a good place to include that extra SCRA-specific static information? 

i.e. 
{
  "scra": {
       "start_date": "jan 2",
       "expected_end_date": "Aug 2",
       "other_scra_foo": "bar"
   }
}

2022-01-10 15:41 UTC, phorical commented
I like where you're going with that, and I think that's a good idea but probably a Day 2 thing. I would love to get the functionality out into the open for testing/BHG first, then expand on top of it with additional functionality/improvements.

2022-01-10 15:51 UTC, ps2-controller commented
Sounds good!

2022-01-10 15:52 UTC, merged